fix issue with null byte string by dumping it first
CycloneDX/cyclonedx-cocoapods pull request #86
Opened 2024-12-17 09:37 UTC by fnxpt

Fixes #85

2024-12-20 04:38 UTC, macblazer requested changes

2024-12-20 04:38 UTC, macblazer commented on lib/cyclonedx/cocoapods/bom_builder.rb
> +          xml.description { xml.cdata description.dump[1..-2] } unless description.nil?
Might be nice to add a comment on the line above this something along the lines of

```
# Use `dump` to escape non-printing characters, then remove the starting and trailing double-quotes from `dump`.
```

Also, would be nice to have a unit test that sets up a pod with a description that contains a null byte in the middle so we can be sure this continues to solve the problem.

2024-12-21 08:08 UTC, jkowalleck commented
> Codacy complaint, but the code looks good semantically. Thanks for adding the unit test.

codacy says: 
> https://app.codacy.com/gh/CycloneDX/cyclonedx-cocoapods/pull-requests/86/issues#issue-85bd871545c6bc02d711a60bd6884ec5
> Line is too long. [122/120]

2025-01-06 13:26 UTC, fnxpt commented
Can we merge this?

2025-01-07 01:25 UTC, merged